add_newline = false

format = """$hostname$directory$git_branch$git_status$character"""

[package]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 2
truncate_to_repo = false

[aws]
disabled = true

[line_break]
disabled = true

[character]
success_symbol = "[γ](white)"
error_symbol = "[γ](red)"

# Languages to disable, cause I want that right now
[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[nim]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[zig]
disabled = true
