# Additional git repositories to pull
#git_repos = [
#    "~/src/*/",
#    "~/.config/something"
#]

# Same options as the command line flag
#disable = ["system", "emacs"]
disable = ["go", "node"]

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
#ssh_arguments = "-o ConnectTimeout=2"

# Arguments to pass Git when pulling Repositories
#git_arguments = "--rebase --autostash"

# Do not set the terminal title
#set_title = false
# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
#[commands]
#"Python Environment" = "~/dev/.env/bin/pip install -i https://pypi.python.org/simple -U --upgrade-strategy eager jupyter"
