# keymap = """
#     xkb_keymap {
#         xkb_keycodes { include "evdev+aliases(qwerty)" };
#         xkb_types    { include "complete"              };
#         xkb_compat   { include "complete"              };
#         xkb_symbols  { include "pc+us+inet(evdev)"     };
#     };
#     """
keymap.rmlvo = { layout = "us", variants = "" }

on-graphics-initialized = [
  { type = "exec", exec = "/usr/lib/pam_kwallet_init" },
  # { type = "exec", exec = "mako" },
  # { type = "exec", exec = "wl-tray-bridge" },
  { type = "exec", exec = "wayland-pipewire-idle-inhibit" },
  { type = "exec", exec = ["xrandr", "--output", "DP-3", "--primary"] },
  { type = "exec", exec = ["vicinae", "server"] },
  { type = "exec", exec = ["solaar", "-w", "hide"] },
  { type = "exec", exec = ["discord"] },
  { type = "exec", exec = ["signal-desktop", "--password-store=kwallet6"] },
  { type = "exec", exec = ["steam"] },
  { type = "exec", exec = ["firefox"] },
  { type = "exec", exec = ["noctalia", "--daemon"] },
]

show-bar = false
show-titles = false

auto-reload = true

idle = { minutes = 10, grace-period = { seconds = 3 } }
on-idle = { type = "exec", exec = { shell = "noctalia msg session lock" } }

window-management-key = "Super_L"

direct-scanout = true

render-device.name = "dedicated"

[env]
XDG_CURRENT_DESKTOP = "jay"
xDG_SESSION_TYPE = "wayland"
XDG_SESSION_DESKTOP = "jay"
XDG_MENU_PREFIX = "arch-"

PROTON_DXVK_LOWLATENCY = "1"

DXVK_FRAME_PACE = "low-latency-vrr-340"
DXVK_FRAME_RATE = "340"

VKD3D_FRAME_RATE = "340"
PROTON_VKD3D_LOWLATENCY = "1"
VKD3D_CONFIG = "descriptor_heap"
VKD3D_SWAPCHAIN_PRESENT_MODE = "FIFO"

ENABLE_LAYER_MESA_ANTI_LAG = "1"
RADV_EXPERIMENTAL = "heap"

[theme]
container-borders = "full"
border-width = 1

[[drm-devices]]
name = "dedicated"
match = { pci-vendor = 0x1002, pci-model = 0x7550 }
plane-color-pipelines = true

[[inputs]]
match.is-pointer = true
accel-profile = "Flat"
accel-speed = 0.0

[[outputs]]
name = "right"
match.connector = "DP-3"
x = 1920
y = 0
mode = { width = 2560, height = 1440, refresh-rate = 359.979 }
vrr = { mode = "variant1", cursor-hz = 90 }
tearing.mode = "variant1"

[[outputs]]
name = "left"
match.connector = "HDMI-A-1"
x = 0
y = 0
mode = { width = 1920, height = 1080, refresh-rate = 100.0 }

[[windows]]
match.x-class = "discord"
match.just-mapped = true
action = { type = "move-to-workspace", name = "5" }

[[windows]]
match.app-id = "signal"
match.just-mapped = true
action = { type = "move-to-workspace", name = "5" }

[[windows]]
match.x-class = "steam"
match.just-mapped = true
action = { type = "move-to-workspace", name = "3" }

[[windows]]
match.app-id = "solaar"
match.just-mapped = true
action = { type = "move-to-workspace", name = "2" }

# [[windows]]
# match.app-id = "firefox"
# match.just-mapped = true
# action = { type = "move-to-workspace", name = "4" }

[color-management]
enabled = true

# [[clients]]
# match.any = [{ comm = "wl-copy" }, { comm = "wl-paste" }]
# match.sandboxed = false
# capabilities = "data-control"
#
# [[clients]]
# name = "grim"
# capabilities = "screencopy"
#
# [[clients]]
# name = "slup"
# capabilities = "layer-shell"


[workspaces."1"]
initial-output.connector = "DP-3"
[workspaces."2"]
initial-output.connector = "DP-3"
[workspaces."3"]
initial-output.connector = "DP-3"
[workspaces."4"]
initial-output.connector = "HDMI-A-1"
[workspaces."5"]
initial-output.connector = "HDMI-A-1"

[shortcuts]
alt-h = "focus-left"
alt-j = "focus-down"
alt-k = "focus-up"
alt-l = "focus-right"

alt-shift-h = "move-left"
alt-shift-j = "move-down"
alt-shift-k = "move-up"
alt-shift-l = "move-right"

alt-z = "split-horizontal"
alt-v = "split-vertical"

alt-t = "toggle-split"
alt-m = "toggle-mono"
alt-u = "toggle-fullscreen"

alt-f = "focus-parent"
alt-c = "open-control-center"
alt-shift-c = "close"
alt-shift-f = "toggle-floating"
logo-Return = { type = "exec", exec = "wezterm-gui" }
alt-space = { type = "exec", exec = { prog = "vicinae", args = [
  "toggle",
], privileged = true } }
alt-shift-x = "quit"
alt-shift-r = "reload-config-toml"
logo-e = { type = "exec", exec = { prog = "dolphin", env = { XDG_CURRENT_DESKTOP = "KDE" } } }

alt-shift-s = { type = "exec", exec = { shell = "grim -g \"$(slurp)\" - | wl-copy --type image/png" } }
Print = { type = "exec", exec = { shell = "grim -o DP-3 \"$(xdg-user-dir PICTURES)/$(date +'%s_grim.png')\"" } }

logo-l = { type = "exec", exec = { shell = "noctalia msg session lock" } }

alt-shift-e = { type = "exec", exec = [
  "noctalia",
  "msg",
  "panel-toggle",
  "session",
] }

alt-shift-d = { type = "exec", exec = ["/home/alex/bin/jay-hdr-swap.sh"] }

alt-shift-b = { type = "exec", exec = [
  "jay",
  "randr",
  "output",
  "HDMI-A-1",
  "enable",
] }

ctrl-alt-F1 = { type = "switch-to-vt", num = 1 }
ctrl-alt-F2 = { type = "switch-to-vt", num = 2 }
ctrl-alt-F3 = { type = "switch-to-vt", num = 3 }
ctrl-alt-F4 = { type = "switch-to-vt", num = 4 }
ctrl-alt-F5 = { type = "switch-to-vt", num = 5 }
ctrl-alt-F6 = { type = "switch-to-vt", num = 6 }
ctrl-alt-F7 = { type = "switch-to-vt", num = 7 }
ctrl-alt-F8 = { type = "switch-to-vt", num = 8 }
ctrl-alt-F9 = { type = "switch-to-vt", num = 9 }
ctrl-alt-F10 = { type = "switch-to-vt", num = 10 }

alt-1 = [{ type = "show-workspace", name = "1" }, "warp-mouse-to-focus"]
alt-2 = [{ type = "show-workspace", name = "2" }, "warp-mouse-to-focus"]
alt-3 = [{ type = "show-workspace", name = "3" }, "warp-mouse-to-focus"]
alt-4 = [{ type = "show-workspace", name = "4" }, "warp-mouse-to-focus"]
alt-5 = [{ type = "show-workspace", name = "5" }, "warp-mouse-to-focus"]
alt-6 = [{ type = "show-workspace", name = "6" }, "warp-mouse-to-focus"]
alt-7 = [{ type = "show-workspace", name = "7" }, "warp-mouse-to-focus"]
alt-8 = [{ type = "show-workspace", name = "8" }, "warp-mouse-to-focus"]
alt-9 = [{ type = "show-workspace", name = "9" }, "warp-mouse-to-focus"]
alt-0 = [{ type = "show-workspace", name = "10" }, "warp-mouse-to-focus"]

alt-shift-1 = { type = "move-to-workspace", name = "1" }
alt-shift-2 = { type = "move-to-workspace", name = "2" }
alt-shift-3 = { type = "move-to-workspace", name = "3" }
alt-shift-4 = { type = "move-to-workspace", name = "4" }
alt-shift-5 = { type = "move-to-workspace", name = "5" }
alt-shift-6 = { type = "move-to-workspace", name = "6" }
alt-shift-7 = { type = "move-to-workspace", name = "7" }
alt-shift-8 = { type = "move-to-workspace", name = "8" }
alt-shift-9 = { type = "move-to-workspace", name = "9" }
alt-shift-0 = { type = "move-to-workspace", name = "10" }

[complex-shortcuts]
XF86AudioRaiseVolume = { action.type = "exec", action.exec.shell = "noctalia msg volume-up", repeat = true, allow-locked = true }
XF86AudioLowerVolume = { action.type = "exec", action.exec.shell = "noctalia msg volume-down", repeat = true, allow-locked = true }
XF86AudioMute = { action.type = "exec", action.exec.shell = "noctalia msg volume-mute", repeat = true, allow-locked = true }

[[clients]]
capabilities = "all"

[[windows]]
match.any = [
  # { app-id = "com.shellyorg.shelly" },
  # { app-id = "org.kde.dolphin" },
  { x-class = "steam", not.title-regex = "^[Ss]team$" },
  { title-regex = "^Steam Settings$" },
  { title-regex = "^(Open File)(.*)$" },
  { title-regex = "^(Select a File)(.*)$" },
  { title-regex = "^(Choose wallpaper)(.*)$" },
  { title-regex = "^(Open Folder)(.*)$" },
  { title-regex = "^(Save As)(.*)$" },
  { title-regex = "^(Library)(.*)$" },
  { title-regex = "^(File Upload)(.*)$" },
  { title-regex = "(.*)(wants to save)$" },
  { title-regex = "^(Select EXE to Run)(.*)$" },
  { title-regex = "^(pavucontrol)$" },
  { title-regex = "^.*Welcome$" },
  { title-regex = "^(Copying — Dolphin)$" },
  { title-regex = "^.*is sharing (a window|your screen).*$" },
  { title-regex = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$" },
]
initial-tile-state = "floating"
